### ISSUE TITLE
Update ? 

### ISSUE THREAD

**Issue by xxzozaxx** [evbogdanov/acme#3]
hi, 
Did you write any new scirpts since last commit, if you did, could you plzz add them

also, thanks for all these awesome scripts,

**Comment by evbogdanov** [comment]
Hello.

I don't use Acme at the moment. Maybe one day I'll switch back to it and add more useful scripts.

Meanwhile, you can write scripts yourself. It's so much fun because Acme doesn't care which programming language you choose. Bash, Python, C... It really doesn't matter; literally anything will do!

**Comment by xxzozaxx** [comment]
Thanks,
Sure I will do.

if you could't mind to talk about what make you leave acme, this may be great.

thanks again

**Comment by evbogdanov** [comment]
I didn't "leave" Acme. I like it a lot. Unfortunately, at my current work I'm stuck with one of those modern bloated IDEs.
