### ISSUE TITLE
Scripts doesn't work inside acme

### ISSUE THREAD

**Issue by helloandrey** [evbogdanov/acme#4]
Hi, could you help me to understand how to use scripts inside acme? 

For example, `i`. It is in my `$PATH`, I'm trying to execute it on selected text inside acme, but nothing is happening, could you please tell me what I'm doing wrong?

If I do `>i` it puts selected text inside new window with indentation, but how to get it inside current window/buffer?

_P.S. Thank you for a great repository about acme editor!_

**Comment by evbogdanov** [comment]
Hi.

`i` works like a regular shell script. You can try it in your terminal by piping some text:

```bash
echo some text | i
# The output will be `    some text` with a leading tab character
```

So, in order to indent selected text inside Acme, you just middle-click `|i`

<img width="369" alt="Screenshot 2020-05-23 at 16 56 27" src="https://user-images.githubusercontent.com/5017179/82732769-f648db80-9d17-11ea-8472-e8d38780e89c.png">

**Comment by helloandrey** [comment]
Got it! Thank you! It works now. I didn't know about `|`, only learned how to use `<` and `>` with an external scripts. This is fantastic!

Thank you! :-)

**Comment by evbogdanov** [comment]
You're welcome. Have fun with Acme!
